# -*- coding: utf-8 -*-
"""programming_dhcss_exercise_w12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18FuFH8MO9lGjI1Y4viRT02TFz0AaPCu6

Programming for DHCSS Exercises: Week 10. Data Visualization

(coppied/adapted from [Pierian Data](https://github.com/mwesterby/complete-python-bootcamp/blob/main/11.%20Web%20Scraping/11.3%20Web%20Scraping%20Exercises.ipynb))
"""

### Problem 1: Import any libraries you think you'll need to scrape a website

### Write your code here

### Problem 2: Connect to http://quotes.toscrape.com/ and get the HMTL text from the page

### Write your code here

### Problem 3: Get the names of all the authors on the first page

### Write your code here

### Problem 4: Create a list of all the quotes on the first page

### Write your code here

"""Now, note that there are more than one page, and subsequent pages look like: http://quotes.toscrape.com/page/2/
- You will need to figure out how to check that your loop is on the last page with quotes
- For the sake of our exercise, note that we have 10 pages
- Pages exist after 10 but look like: http://quotes.toscrape.com/page/11/
"""

### Problem 5: Loop through all the pages and get all the unique authors on the website

### Write your code here