# -*- coding: utf-8 -*-
"""programming_dhcss_exercise_w12_solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FDpUafrKqJsYleTMUjgTW0K4GyLEowzv

Programming for DHCSS Exercises: Week 10. Data Visualization

(coppied/adapted from [Pierian Data](https://github.com/mwesterby/complete-python-bootcamp/blob/main/11.%20Web%20Scraping/11.3%20Web%20Scraping%20Exercises.ipynb))
"""

### Problem 1: Import any libraries you think you'll need to scrape a website

### Write your code here

import requests
from bs4 import BeautifulSoup

### Problem 2: Connect to http://quotes.toscrape.com/ and get the HMTL text from the page

### Write your code here

res = requests.get('http://quotes.toscrape.com/')
soup = BeautifulSoup(res.text)
soup

### Problem 3: Get the names of all the authors on the first page

### Write your code here

authors = []
author_tags = soup.find_all('small')
for i in author_tags:
  authors.append(i.text)

authors

### Problem 4: Create a list of all the quotes on the first page

### Write your code here

quotes = []
text_tags = soup.find_all(class_ = 'text')
for i in text_tags:
    quotes.append(i.text)

quotes

"""Now, note that there are more than one page, and subsequent pages look like: http://quotes.toscrape.com/page/2/
- You will need to figure out how to check that your loop is on the last page with quotes
- For the sake of our exercise, note that we have 10 pages
- Pages exist after 10 but look like: http://quotes.toscrape.com/page/11/
"""

### Problem 5: Loop through all the pages and get all the unique authors on the website

### Write your code here

current_page = 1
authors = []

while True:

  print(current_page)
  url = f'http://quotes.toscrape.com/page/{current_page}/'

  res = requests.get(url)
  soup = BeautifulSoup(res.text)
  author_tags = soup.find_all('small')

  if len(author_tags) == 0:
    break

  for author in author_tags:
      authors.append(author.text)

  current_page += 1

for author in authors:
    print(author)