# -*- coding: utf-8 -*-
"""programming_dhcss_exercise_w3_solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZJ1MIMnQd9IVtSBE-8lAlKJz1-wpub9K

Programming for DHCSS Exercises: Week 3. Strings, Lists, Tuples, and More
"""

### Problem 1 ###

### Slice the first list to get the second

first_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

second_list = [1, 4, 7]

### Write your code here

print(first_list[0: len(first_list): 3])
print(first_list[0::3]) # you can skip the stop argument (start:stop:step)

### Problem 2 ###

### Given the follwoing list of numbers, write a program that turns every item in the list into its square

numbers = [1, 2, 3, 4, 5, 6, 7]

### Write a program relying on for loop

numbers_squared = []
for i in numbers:
  numbers_squared.append(i ** 2)
print(numbers_squared)

### Write a program relying on list comprehension

numbers_squared = [i **2 for i in numbers]
print(numbers_squared)

### Problem 3 ###

### First, use list comprehension to add the two lists index-wise

### Hint: you can use zip() to bind the two lists

list_1 = ['Causa', 'i', 'differ', 'fr', 'correlat']
list_2 = ['tion', 's', 'ent', 'om', 'ion']

### The follwoing is the expected output

['Causation', 'is', 'different', 'from', 'correlation']

### Then, concatenate the elements in the output

['Causation is different from correlation']

### Write your code here

list_3 = [i + j for i, j in zip(list_1, list_2)]
print(list_3)
' '.join(list_3)

list_wrong = [i + j for i in list_1 for j in list_2] # see what it does
print(list_wrong)
' '.join(list_wrong)

### Problem 4 ###

### Write a program to add two integer items, 7000 and 8000, after 6000 in the following list

nested_list = [True, 10, 20, [300, 400, [5000, 6000], 500], 30, None]

### The following is the expected output

[True, 10, 20, [300, 400, [5000, 6000, 7000, 8000], 500], 30, None]

### Hint : nested_list[3][2] = [5000, 6000]

### Write your code here

nested_list[3][2].extend([7000, 8000])
print(nested_list)

### Problem 5a-c ###

### You will do some quick analysis on tweets data

### First get text data from an URL

import requests
url = 'https://raw.githubusercontent.com/harshilkamdar/trump-tweets/master/trump.txt'

response = requests.get(url) # Fetch the text file content
text_data = response.text # Decode the content
tweets = text_data.split('\n') # Split the content by lines

### Examine the data

print(type(tweets))
print(tweets[0])
print(len(tweets))

### Exercise 5a: use list comprehension to create a list to record whether tweets are a retweet or not (i.e. whether it starts with "RT" or not),
### and count the number of retweets

### Write your code here

retweet_or_not = [tweet.startswith("RT") for tweet in tweets]
sum(retweet_or_not)

### Exercise 5b: use list comprehension to create a list to record whether tweets contain an URL or not,
### and count the number of tweets with at least one URL

### Write your code here

has_url_or_not = ["http://" in tweet for tweet in tweets]
sum(has_url_or_not)

### Exercise 5c: create a list to record the number of occurrences for "trump"

### Write your code here

count_trump = [tweet.lower().count("trump") for tweet in tweets]
import numpy as np
print(np.mean(count_trump))
print(np.median(count_trump))

### Problem 6a-b ###

### Create a list of YT comments

youtube_comments = [
    "Awesome video, thanks for sharing! @channel",
    "I really learned a lot from this, @channel!",
    "@user1 @user2 have you guys seen this?",
    "Terrible content. Unsubscribed.",
    "Pls make more content like this! @channel",
    "I totally agree with @user3.",
    "Your videos are always so insightful, @channel.",
    "Could you talk about XYZ in the next video?",
    "I've been following you since 100 subs, @channel.",
    "@user3 I think you're mistaken."
]

### Exercise 6a: filter positive comments: create a new list containing only the comments that include the words "awesome", "thanks", or "learned". Use list comprehension.
### Hint: you can use "any()" function as we have three keywords: https://www.w3schools.com/python/ref_func_any.asp
### Write your code here

l_post = ['awesome', 'thanks', 'learned']
youtube_comments_pos = [comment for comment in youtube_comments if any(word in comment.lower() for word in l_post)]

### Exercise 6b: count the total number of mentions (e.g., @username) across all comments
### Write your code here

l_mention = [[word for word in comment.split() if word.startswith('@')] for comment in youtube_comments]
l_mention_count = [len(sub_l) for sub_l in l_mention]
sum(l_mention_count)

### Problem 7 ###

### Write a program that produces a matrix like the following:

matrix = [[0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4]]

### Write your code here

matrix = [[j for j in range(5)] for i in range(5)]
print(matrix)