# -*- coding: utf-8 -*-
"""programming_dhcss_exercise_w2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g6jY46c7AOC42z1R8X91VdqAJ-5Rp3na

Programming for DHCSS Exercises: Week 2. Branching and Iteration
"""

### Problem 1 ###

### Using the variables below, write a code that generates the following string: "umbrella ella ella ella "

once = "umbr"
repeat = "ella"

### Write your code here

### Problem 2 ###

### Using a for loop write a code that counts the number of characters in the string named "example_string"

example_string = "World’s largest rice exporter’s abrupt ban has triggered global panic - but its own farmers are bearing the brunt"

### Start with a counter variable

count = 0

### Write your code here

### Problem 3 ###

### Suppose you wanted to multiply a number (here, 1) by 2 and keep iterating that until the product of the numbers exceeds 150

### Use a while loop and print the result (the multipied number) from each iteration

number = 1

### Write your code here

### Problem 4 ###

### Write a for loop which prints "Hello!, " plus each name in the following list. i.e.: "Hello, Sam!"

lst = ["Sam", "Lisa", "Micha", "Dave", "Wyatt", "Emma", "Sage"]

### Also, do the same but only when the name invovles "e" (you can use "in" operator for this)

### Write your code here

### Problem 5 ###

### You will get data on news articles.

### Write a for loop to go through the "month" column and count the number of articles that were published in April or December

### Run this code to get the data

import pandas as pd # import pandas library shortened as pd
url = "https://github.com/taegyoon-kim/programming_dhcss_23fw/raw/main/week_2/news_category.xlsx" # string containig the url
df = pd.read_excel(url) # read_excel function to read xlsx files

### Check the data

print(type(df))
print(df.head(5)) # method that shows the first N (=5) rows of the data
print(df.dtypes) # data type for each column

### The "month" column can be accessed like the following

df['month']

### Write your code here

### Problem 6 ###

### Use the same data to write a code that counts the number of articles by "theme" using a for loop and if, elif, and else statements

### Use the following counters for each category: Politics, Entertainment, and Others

count_politics = 0
count_entertainment = 0
count_others = 0

### Write your code here

# Problem 7

### With the same data, write a for loop code to creaet a list containing the word count for articles

### Exclude articles with too few words (<50) or too many words (>500)

### You create an empty list named "word_counts" and append the word count from each iteration (you can use "append" method within the loop)

word_counts = []

### See below for how append() works

empty_lst = []
for i in range(0, 3):
  empty_lst.append(i)
print(empty_lst)

### Use split() method to parse an article text into words

text = 'this is a text'
text_spt = text.split()
print(text_spt)

### Skip the outliers usings statements like break, continue, or pass (<50 or >500)

### Write your code here

### Problem 8 ###

### You are given two lists, one containing names of fruits and the other containing their corresponding colors.

### Write a for loop code that prints a statement like the following

### E.g.,: "The color of Apple is Red."

### If the fruit's name is great than 5 characters, just print "Too long."

### Consider using "zip()"

fruits = ['Apple', 'grape', 'Cherry', 'Avocado']
colors = ['Red', 'Green', 'Red', 'Brown', 'Green']

### Write your code here

### Problem 9 ###

### Write a code that extracts hashtags from the following list of tweet texts

### Hashtags in tweets are words that start with the symbol #

### You are given a list of tweet texts

tweets = [
    "Learning Python is fun! #Python #coding",
    "Data science is awesome. #datascience #machinelearning",
    "Artificial Intelligence: The future! #AI #future",
    "Study at KAIST for #CT #DHCSS #DS"]

### Initialize an empty list to store hashtags (and append exracted hashtags to it!)

hashtags = []

### Use a for loop to iterate through tweets

### Inside the loop, use another for loop to iterate through words in a given tweet

### Use conditional statements to identify whether a word is a hashtag

### Hint I: use split a tweet into a list of words using split() method

### Hint II: use startswith() method to see if a word is a hashtag or not

### Write your code here